// src/components/Footer.vue
<script>

</script>

<template>
    <footer>
        <hr>
        <div class="footer-heading">
            <h1>that's it!</h1>
            <p>~ thanks for coming through ~</p><br>
        </div>
        
        <div class="headshot">

        </div>
        <div class="footer-byline">
            <span class="copywrite">Copyright © 2021 E. Conrad Diao. All rights reserved.</span>
            <span> Hastily made with 🖤 and ☕️ by <a href="https://linkedin.com/in/conraddiao">@econraddiao</a>.</span>
        </div>
    </footer>
</template>

<style>
footer {
    padding: 1rem;
}

.footer-heading {
    text-align: center;
}
.footer-byline {
    display: flex;
    flex-flow: row wrap-reverse;
    justify-content: space-between;
    align-items: baseline;
}
.copywrite {
    color : var(--color-three)
}

</style>

// src/Footer.jsx
import React from 'react';
import './Footer.css';

const Footer = () => {
  return (
    <footer>
      <hr />
      <div className="footer-heading">
        <h1>that's it!</h1>
        <p>~ thanks for coming through ~</p>
        <br />
      </div>

      <div className="headshot">
        {/* Add an image or style this div if needed */}
      </div>

      <div className="footer-byline">
        <span className="copywrite">Copyright © 2025 E. Conrad Diao. All rights reserved.</span>
        <span>
          Hastily made with 🖤 and ☕️ by{' '}
          <a href="https://linkedin.com/in/conraddiao">@econraddiao</a>.
        </span>
      </div>
    </footer>
  );
};

export default Footer;
