// src/components/Honorific.vue
<script>
    export default {
        name: 'Honorific',
        inject: ['honorifics'],
        data() {
            return {
                btitle: String,
                bcolor: {backgroundColor: String}
            }
        },
        mounted() {
            setInterval(() => {
                let index = Math.floor(Math.random() * this.honorifics.value.length);
                this.btitle = this.honorifics.value[index].title;
                this.bcolor.backgroundColor = this.honorifics.value[index].color;
            }, 200);
            
        }
    }
</script>

<template>
    <span :style="this.bcolor">&nbsp;{{btitle}}&nbsp;</span>
</template>

<style scoped>
    span {
        font-family: 'IBM Plex Mono', monospace;
        font-style: normal;
        color: white;
    }
</style>

// src/Honorific.jsx

import React, { useEffect, useState } from 'react';
const Honorific = ({ honorifics }) => {
  const [title, setTitle] = useState('');
  const [bgColor, setBgColor] = useState('');

  useEffect(() => {
    const interval = setInterval(() => {
      if (honorifics && honorifics.length) {
        const index = Math.floor(Math.random() * honorifics.length);
        setTitle(honorifics[index].title);
        setBgColor(honorifics[index].color);
      }
    }, 200);

    return () => clearInterval(interval);
  }, [honorifics]);

  return (
    <span
      style={{
        backgroundColor: bgColor,
        fontFamily: "'IBM Plex Mono', monospace",
        fontStyle: 'normal',
        fontWeight: 200,
        color: 'white',
      }}
    >
      &nbsp;{title}&nbsp;
    </span>
  );
};

export default Honorific;
